##########
# WINDOW #
##########

[window]

# Padding
padding = { x = 5, y = 5 }

# Opacity
opacity = 0.98

########
# FONT #
########

[font]

# Normal font style
normal = { family = "ZedMono Nerd Font", style = "Regular" }

# Bold font style
bold = { style = "Bold" }

# Italic font style
italic = { style = "Italic" }

# Bold Italic font style
bold_italic = { style = "Bold Italic" }

# Font size in points
size = 16
