command_timeout = 10000

format = """
$os\
$username\
$hostname\
$localip\
$shlvl\
$shell\
$env_var\
$sudo\
$character\
"""

right_format = """
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$crystal\
$custom\
$jobs\
$status\
$container\
$battery\
$time\
"""

add_newline = true

[character]
format = "$symbol "
success_symbol = "[◉](bold italic bright-green)"
error_symbol = "[✗](bold italic bright-red)"

[env_var.VIMSHELL] # vim subshell
format = "[$env_value]($style)"
style = 'green italic'

[sudo]
format = "[$symbol]($style)"
style = "italic bright-purple"
symbol = "◇┈"
disabled = false

[os]
disabled = false

[os.symbols]
Windows = "󰍲 "
Ubuntu = "󰕈 "
SUSE = " "
Raspbian = "󰐿 "
Mint = "󰣭 "
Macos = "󰀵 "
Manjaro = " "
Linux = "󰌽 "
Gentoo = "󰣨 "
Fedora = "󰣛 "
Alpine = " "
Amazon = " "
Android = " "
Arch = "󰣇 "
Artix = "󰣇 "
CentOS = " "
Debian = "󰣚 "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "

[username]
show_always = true
style_user = "bold bright-yellow"
style_root = "bold purple italic"
format = "[$user]($style) "
disabled = false

[directory]
home_symbol = ""
truncation_symbol = "▦ "
read_only = " "
style = "italic blue"
format = ' [$path]($style)[$read_only]($read_only_style)'

[jobs]
format = "[ $symbol$number]($style)"
style = "white"
symbol = "[▶ ](blue italic)"

[localip]
ssh_only = true
format = " ◯[$localipv4](bold magenta)"
disabled = false

[time]
disabled = false
format = "[$time]($style)"
time_format = "%R"
utc_time_offset = "local"
style = "dimmed white"

[git_branch]
format = "[ $symbol $branch(:$remote_branch)]($style) "
symbol = "[](bold purple)"

[memory_usage]
symbol = "󰍛 "
format = " [${ram}( ${swap})]($style)"

[package]
format = " [$symbol$version]($style)"
version_format = "${major}.${minor}"
symbol = "󰏗 "
style = "bright-yellow italic"

[lua]
format = " [${symbol}${version}]($style)"
symbol = "󰢱 "
style = "italic bright-yellow"

[nodejs]
format = " [󰎙 ($version)](italic bright-green)"
detect_files = ["package-lock.json", "yarn.lock"]
version_format = "${major}.${minor}"

[python]
format = " [${symbol}${version}]($style)"
symbol = "󰌠 "
version_format = "${major}.${minor}"
style = "italic bright-yellow"

[ruby]
format = " [${symbol}${version}]($style)"
symbol = "󰴭 "
version_format = "${major}.${minor}"
style = "italic red"

[rust]
format = " [$symbol$version]($style)"
symbol = "󱘗 "
version_format = "${major}.${minor}"
style = "italic red"

[swift]
format = " [${symbol}${version}]($style)"
symbol = "󰛥 "
style = "italic bright-red"
version_format = "${major}.${minor}"

[aws]
format = " [$symbol $profile $region]($style)"
style = "italic blue"
symbol = "󰸏 "

[c]
symbol = " "
format = " [$symbol($version(-$name))]($style)"

[dart]
symbol = " "
format = " [$symbol($version )]($style)"

[docker_context]
symbol = "󰡨 "
format = " [$symbol$context]($style)"

[elixir]
symbol = " "
format = " [$symbol $version OTP $otp_version ]($style)"

[elm]
symbol = " "
format = " [$symbol($version )]($style)"

[golang]
symbol = " "
format = " [$symbol($version )]($style)"

[haskell]
symbol = "󰲒 "
format = " [$symbol($version )]($style)"

[java]
symbol = "󰬷 "
format = " [${symbol}(${version} )]($style)"

[julia]
symbol = " "
format = " [$symbol($version )]($style)"

[nix_shell]
symbol = "󱄅 "
format = " [$symbol$state $name]($style)"
