command_timeout = 10000

format = """
$os\
$hostname\
$localip\
$username\
$sudo\
$character\
"""

right_format = """
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$crystal\
$custom\
$jobs\
$status\
"""

add_newline = true

[hostname]
format = "[$ssh_symbol$hostname]($style) "

[localip]
format = "[󰢹 $localipv4](bold fg:#ae81ff) "
disabled = false

[username]
show_always = true
style_user = "bold bright-yellow"
style_root = "bold bright-purple"
format = "[$user]($style) "
disabled = false

[sudo]
format = "[$symbol]($style)"
style = "italic bright-purple"
symbol = " "
disabled = false

[character]
format = "$symbol "
success_symbol = "[◉](bold italic bright-green)"
error_symbol = "[✗](bold italic bright-red)"

[directory]
home_symbol = " "
truncation_symbol = " "
read_only = " "
style = "bold italic blue"
format = ' [$path]($style)[$read_only]($read_only_style)'

[git_branch]
format = "[ $symbol $branch(:$remote_branch)]($style) "
symbol = "[](bold purple)"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[memory_usage]
symbol = "󰍛 "
format = " [${ram}( ${swap})]($style)"

[package]
format = " [$symbol$version]($style)"
version_format = "${major}.${minor}.${patch}"
symbol = "󰏗 "

[lua]
format = " [${symbol}${version}]($style)"
symbol = "󰢱 "

[nodejs]
format = " [$symbol$version]($style)"
symbol = "󰎙 "
detect_files = ["package-lock.json", "yarn.lock"]
version_format = "${major}.${minor}.${patch}"

[python]
format = " [${symbol}${version}]($style)"
symbol = "󰌠 "
version_format = "${major}.${minor}"

[ruby]
format = " [${symbol}${version}]($style)"
symbol = "󰴭 "
version_format = "${major}.${minor}"

[rust]
format = " [$symbol$version]($style)"
symbol = "󱘗 "
version_format = "${major}.${minor}"
style = "red dimmed"

[swift]
format = " [${symbol}${version}]($style)"
symbol = "󰛥 "
version_format = "${major}.${minor}"

[aws]
format = " [$symbol $profile $region]($style)"
symbol = "󰸏 "

[c]
symbol = " "
format = " [$symbol($version(-$name))]($style)"

[dart]
symbol = " "
format = " [$symbol($version )]($style)"

[docker_context]
symbol = "󰡨 "
format = " [$symbol$context]($style)"

[elixir]
symbol = " "
format = " [$symbol $version OTP $otp_version ]($style)"

[elm]
symbol = " "
format = " [$symbol($version )]($style)"

[golang]
symbol = " "
format = " [$symbol($version )]($style)"

[haskell]
symbol = "󰲒 "
format = " [$symbol($version )]($style)"

[java]
symbol = "󰬷 "
format = " [${symbol}(${version} )]($style)"

[julia]
symbol = " "
format = " [$symbol($version )]($style)"

[nix_shell]
symbol = "󱄅 "
format = " [$symbol$state $name]($style)"

[jobs]
format = " [$symbol$number]($style)"
style = "bold white"
