workspaces:
  entries:
    - name: 1
    - name: 2
    - name: 3
    - name: 4
    - name: 5
    - name: 6
    - name: 7
    - name: 8
    - name: 9

layout_engines:
  entries:
    - type: tree
      initial_direction: right

    - type: slice
      variant:
        type: row

    - type: slice
      variant:
        type: column

    - type: slice
      variant:
        type: primary_stack

    - type: slice
      variant:
        type: secondary_primary_stack

    - type: slice
      variant:
        type: multi_column_stack
        columns: [2, 1, 0]

    - type: slice
      variant:
        type: secondary_primary_stack
        primary_capacity: 1
        secondary_capacity: 2

    - type: focus
      maximize: true

    - type: floating

keybinds:
  entries:
    - command: whim.core.focus_workspace_1
      keybind: alt-1

    - command: whim.core.focus_workspace_2
      keybind: alt-2

    - command: whim.core.focus_workspace_3
      keybind: alt-3

    - command: whim.core.focus_workspace_4
      keybind: alt-4

    - command: whim.core.focus_workspace_5
      keybind: alt-5

    - command: whim.core.focus_workspace_6
      keybind: alt-6

    - command: whim.core.focus_workspace_7
      keybind: alt-7

    - command: whim.core.focus_workspace_8
      keybind: alt-8

    - command: whim.core.focus_workspace_9
      keybind: alt-9

  unify_key_modifiers: true

filters:
  entries: []

routers:
  routing_behavior: route_to_launched_workspace

plugins:
  bar:
    left_components:
      entries:
        - type: workspace_widget

    center_components:
      entries:
        - type: focused_window_widget
          shorten_title: true

    right_components:
      entries:
        - type: active_layout_widget
        - type: date_time_widget
          format: HH:mm:ss, dd MMM yyyy
        - type: tree_layout_widget

  floating_window:
    is_enabled: true

  gaps:
    is_enabled: true
    outer_gap: 5
    inner_gap: 5
    default_outer_delta: 2
    default_inner_delta: 2

  command_palette:
    is_enabled: true
    max_height_percent: 40
    max_width_pixels: 800
    y_position_percent: 20

  focus_indicator:
    is_enabled: true
    border_size: 2
    is_fade_enabled: true
    fade_timeout: 2
    color: red

  layout_preview:
    is_enabled: true

  updater:
    is_enabled: true
    release_channel: alpha
    update_frequency: monthly